# Generated by Django 3.1 on 2020-09-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='musinsa',
            new_name='product',
        ),
    ]
