# Generated by Django 3.1 on 2020-09-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='musinsaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_musinsa', models.TextField()),
                ('musinsaImage', models.ImageField(blank=True, upload_to='')),
                ('musinsaUrl', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='imagesearch',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='article',
            name='musinsaImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
